### ISSUE TITLE
Generate error

### ISSUE THREAD

**Issue by baronha** [oblador/react-native-vector-image#27] opened 2022-05-06 09:17 UTC
<img width="740" alt="Screen Shot 2022-05-06 at 16 15 41" src="https://user-images.githubusercontent.com/23580920/167103608-862038bf-af01-4e1e-a1ac-b2edc60cea10.png">

```
"react-native-vector-image": "^0.3.3",
"@klarna/react-native-vector-drawable": "^0.3.0",
```

**Comment by oblador** [comment] 2022-06-22 14:06
Hi, can you provide a minimal reproducible example?

**Comment by oblador** [comment] 2022-10-30 11:33
Closing due to lack of replies

**Closed by oblador** 2022-10-30 11:33 UTC
